replicaCount: 2

ui:
  message: "Hola Mundo me gusta jugar con kubernetes"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: pregunta3.prosaludsocial.site
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 10m
    memory: 64Mi

serviceMonitor:
  enabled: true
  interval: 15s
  additionalLabels:
    release: prometheus
